// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTIw1uKkskLXf_DQN2lTizBlH9CvQB714',
    appId: '1:608315824552:web:105b3e6e381718fd1ce59d',
    messagingSenderId: '608315824552',
    projectId: 'diaryapp-f5e5f',
    authDomain: 'diaryapp-f5e5f.firebaseapp.com',
    storageBucket: 'diaryapp-f5e5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnoSq1eouazyVXXhQ4Ik9F9U2Uz-pmKVY',
    appId: '1:608315824552:android:1de60596e254097a1ce59d',
    messagingSenderId: '608315824552',
    projectId: 'diaryapp-f5e5f',
    storageBucket: 'diaryapp-f5e5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC553u37IcDUEBvDllO2TnhaJ9tsPEZDvg',
    appId: '1:608315824552:ios:2d9818bc5a8f3e5e1ce59d',
    messagingSenderId: '608315824552',
    projectId: 'diaryapp-f5e5f',
    storageBucket: 'diaryapp-f5e5f.firebasestorage.app',
    androidClientId: '608315824552-sar84gb15ikdeqfrf0qnsh6ag59lsskh.apps.googleusercontent.com',
    iosClientId: '608315824552-uo59nn5j47rc5quqf6cslehj75tf4jq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC553u37IcDUEBvDllO2TnhaJ9tsPEZDvg',
    appId: '1:608315824552:ios:2d9818bc5a8f3e5e1ce59d',
    messagingSenderId: '608315824552',
    projectId: 'diaryapp-f5e5f',
    storageBucket: 'diaryapp-f5e5f.firebasestorage.app',
    androidClientId: '608315824552-sar84gb15ikdeqfrf0qnsh6ag59lsskh.apps.googleusercontent.com',
    iosClientId: '608315824552-uo59nn5j47rc5quqf6cslehj75tf4jq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTIw1uKkskLXf_DQN2lTizBlH9CvQB714',
    appId: '1:608315824552:web:922efc49410af9a01ce59d',
    messagingSenderId: '608315824552',
    projectId: 'diaryapp-f5e5f',
    authDomain: 'diaryapp-f5e5f.firebaseapp.com',
    storageBucket: 'diaryapp-f5e5f.firebasestorage.app',
  );

}